from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from random import Random

import numpy as np

from simworld.conflict.model import ConflictContext, choose_conflict_action
from simworld.core.event import Event
from simworld.economy.agriculture import GRAINS, crop_suitability
from simworld.geography.hydrology import Hydrology, derive_hydrology
from simworld.simulation.first_world import FirstWorldConfig, SimulationResult
from simworld.simulation.generational_world import (
    GenerationalSimulationResult,
    GenerationalWorldSimulation,
)
from simworld.simulation.social_world import SocialSimulationResult
from simworld.social.household import Household, Pregnancy, allocate_inheritance, pregnancy_survives
from simworld.social.network import SocialTie
from simworld.social.reproduction import conception_occurs, conception_probability


@dataclass(frozen=True, slots=True)
class CivilizationSimulationResult:
    generational: GenerationalSimulationResult
    hydrology: Hydrology
    crop_suitability: np.ndarray
    households: tuple[Household, ...]
    conflict_actions: dict[str, int]


class CivilizationWorldSimulation(GenerationalWorldSimulation):
    """A deeper vertical slice linking land, households and emergent coercion.

    No conflict is scheduled for narrative reasons. No crop shortage prescribes a policy.
    Households, pregnancies, inheritance and hostile actions are generated by reusable
    state transitions over geography, resources, beliefs and social relations.
    """

    def __init__(self, config: FirstWorldConfig) -> None:
        super().__init__(config)
        self.civil_rng = Random(config.seed ^ 0xC1A11A7E)
        self.hydrology = derive_hydrology(
            self.generated.elevation_m,
            self.generated.water,
            self.generated.rainfall,
        )
        self.grain_suitability = crop_suitability(
            self.generated.fertility,
            self.generated.temperature_c,
            self.generated.rainfall,
            self.hydrology.water_access,
            self.hydrology.ruggedness,
            GRAINS,
        )
        self.households: dict[str, Household] = {}
        self._household_of: dict[str, str] = {}
        self._pregnancies: list[Pregnancy] = []
        self._conflict_grievance: dict[frozenset[str], float] = defaultdict(float)
        self._conflict_actions: dict[str, int] = defaultdict(int)

    def initialize(self) -> None:
        super().initialize()
        if self.households:
            return
        for settlement_id, people in self._settlement_people.items():
            founders = sorted(people)
            for index in range(0, len(founders), 2):
                members = founders[index : index + 2]
                hid = f"hh-{settlement_id[-6:]}-{index // 2 + 1}"
                household = Household(
                    id=hid,
                    settlement_id=settlement_id,
                    food_stock=self.civil_rng.uniform(100.0, 450.0),
                    wealth=self.civil_rng.uniform(0.2, 1.2),
                    debt=self.civil_rng.uniform(0.0, 0.35),
                    land=self.civil_rng.uniform(0.2, 1.4),
                    tools=self.civil_rng.uniform(0.05, 0.45),
                )
                for person_id in members:
                    household.add_member(person_id, 0)
                    self._household_of[person_id] = hid
                    self.world.entities[person_id].attributes["household_id"] = hid
                    self.world.entities[person_id].attributes["personal_wealth"] = self.civil_rng.uniform(0.0, 0.25)
                self.households[hid] = household
                self.world.record_event(
                    Event(
                        kind="household_formed",
                        time=0,
                        participants=tuple(members),
                        locations=(settlement_id,),
                        impact=0.12,
                        payload={"household_id": hid, "members": len(members)},
                    )
                )

    def _local_capacity(self, entity_id: str) -> float:
        base = super()._local_capacity(entity_id)
        cell = self._cells[entity_id]
        crop = float(self.grain_suitability[cell.y, cell.x])
        river = float(self.hydrology.water_access[cell.y, cell.x])
        rugged = float(self.hydrology.ruggedness[cell.y, cell.x])
        return base * (0.72 + 0.42 * crop + 0.12 * river - 0.12 * rugged)

    def _process_due_pregnancies(self, year: int) -> None:
        remaining: list[Pregnancy] = []
        for pregnancy in self._pregnancies:
            if not pregnancy.due(year):
                remaining.append(pregnancy)
                continue
            if not self._alive(pregnancy.gestational_parent_id) or not self._alive(pregnancy.other_parent_id):
                continue
            parent = self.world.entities[pregnancy.gestational_parent_id]
            settlement_id = str(parent.attributes["settlement_id"])
            hid = self._household_of.get(pregnancy.gestational_parent_id)
            household = self.households.get(hid) if hid else None
            food_security = min(1.0, (household.food_stock / 250.0) if household else 0.5)
            health = float(parent.attributes["health"])
            if pregnancy_survives(pregnancy, health, food_security, self.civil_rng):
                child_id = self._birth(
                    year,
                    pregnancy.gestational_parent_id,
                    pregnancy.other_parent_id,
                    settlement_id,
                )
                if household is not None:
                    household.add_member(child_id, year)
                    self._household_of[child_id] = household.id
                    self.world.entities[child_id].attributes["household_id"] = household.id
                    self.world.entities[child_id].attributes["personal_wealth"] = 0.0
            else:
                self.world.record_event(
                    Event(
                        kind="pregnancy_loss",
                        time=year,
                        participants=(pregnancy.gestational_parent_id, pregnancy.other_parent_id),
                        locations=(settlement_id,),
                        impact=0.3,
                        payload={"conceived_at": pregnancy.conceived_at},
                    )
                )
        self._pregnancies = remaining

    def _run_reproduction(self, year: int) -> None:
        self._process_due_pregnancies(year)
        already_pregnant = {p.gestational_parent_id for p in self._pregnancies}
        for gestational_id, other_id, tie in self._active_reproductive_pairs(year):
            if gestational_id in already_pregnant:
                continue
            household = self.households.get(self._household_of.get(gestational_id, ""))
            resource_security = min(1.0, (household.food_stock / 300.0) if household else 0.45)
            intent = max(0.0, min(1.0, 0.42 + 0.22 * tie.sentiment + self.civil_rng.uniform(-0.25, 0.25)))
            probability = conception_probability(
                self._profiles[gestational_id],
                self._profiles[other_id],
                time=year,
                contact_intensity=tie.strength,
                resource_security=resource_security,
                reproductive_intent=intent,
            )
            if conception_occurs(probability, self.civil_rng):
                pregnancy = Pregnancy(
                    gestational_parent_id=gestational_id,
                    other_parent_id=other_id,
                    conceived_at=year,
                    due_at=year + 1,
                    viability=self.civil_rng.uniform(0.78, 0.98),
                )
                self._pregnancies.append(pregnancy)
                settlement_id = str(self.world.entities[gestational_id].attributes["settlement_id"])
                self.world.record_event(
                    Event(
                        kind="conception",
                        time=year,
                        participants=(gestational_id, other_id),
                        locations=(settlement_id,),
                        impact=0.18,
                        payload={"due_at": year + 1, "probability": round(probability, 5)},
                    )
                )

    def _run_household_economy(self, year: int, food_ratio: dict[str, float]) -> None:
        for household in self.households.values():
            living = [person_id for person_id in household.members if self._alive(person_id)]
            if not living:
                continue
            ratio = food_ratio[household.settlement_id]
            production = household.land * (0.7 + 0.5 * ratio) * (0.8 + household.tools)
            consumption = 0.16 * len(living)
            household.food_stock = max(0.0, household.food_stock * 0.55 + 120.0 * production - 80.0 * consumption)
            surplus = max(0.0, household.food_stock - 240.0)
            deficit = max(0.0, 120.0 - household.food_stock)
            household.wealth += surplus / 1500.0
            household.debt += deficit / 1800.0
            if surplus > 0:
                household.food_stock -= 0.25 * surplus

    def _evolve_households(self, year: int) -> None:
        for tie in tuple(self.network.ties):
            if tie.kind not in {"romantic", "intimate", "partner"} or not tie.active_at(year):
                continue
            a, b = tie.source_id, tie.target_id
            if not self._alive(a) or not self._alive(b):
                continue
            ha, hb = self._household_of.get(a), self._household_of.get(b)
            if ha and hb and ha != hb and tie.strength > 0.65 and self.civil_rng.random() < 0.08 + 0.10 * max(0.0, tie.sentiment):
                target, source = self.households[ha], self.households[hb]
                source.remove_member(b)
                target.add_member(b, year)
                self._household_of[b] = target.id
                self.world.entities[b].attributes["household_id"] = target.id
                self.world.record_event(Event(kind="co_residence_changed", time=year, participants=(a, b), locations=(target.settlement_id,), impact=0.15, payload={"household_id": target.id}))
            if tie.sentiment < -0.35 and self.civil_rng.random() < 0.12:
                tie.ended_at = year
                self.world.record_event(Event(kind="relationship_separated", time=year, participants=(a, b), locations=(str(self.world.entities[a].attributes["settlement_id"]),), impact=0.22, payload={"kind": tie.kind}))

    def _inherit_from_deaths(self, year: int, newly_dead: tuple[str, ...]) -> None:
        for person_id in newly_dead:
            entity = self.world.entities[person_id]
            personal = float(entity.attributes.get("personal_wealth", 0.0))
            hid = self._household_of.get(person_id)
            household = self.households.get(hid) if hid else None
            estate = personal + (0.05 * max(0.0, household.net_wealth) if household else 0.0)
            heirs = tuple(child for child in self.kinship.children(person_id) if self._alive(child))
            if not heirs:
                heirs = tuple(sibling for sibling in self.kinship.siblings(person_id) if self._alive(sibling))
            allocations = allocate_inheritance(estate, heirs)
            for heir, amount in allocations.items():
                heir_entity = self.world.entities[heir]
                heir_entity.attributes["personal_wealth"] = float(heir_entity.attributes.get("personal_wealth", 0.0)) + amount
            if allocations:
                self.world.record_event(Event(kind="inheritance_transferred", time=year, participants=(person_id, *allocations.keys()), locations=(str(entity.attributes["settlement_id"]),), impact=0.18 + min(1.0, estate), payload={"estate": round(estate, 5), "heirs": dict(allocations)}))

    def _run_mortality(self, year: int) -> None:
        alive_before = {person_id for person_id in self.person_ids if self._alive(person_id)}
        super()._run_mortality(year)
        newly_dead = tuple(person_id for person_id in alive_before if not self._alive(person_id))
        self._inherit_from_deaths(year, newly_dead)

    def _conflict_context(self, a_id: str, b_id: str, year: int) -> ConflictContext | None:
        a_cell, b_cell = self._cells[a_id], self._cells[b_id]
        path = self.generated.spatial_map.path(a_cell, b_cell, max_expansions=20_000)
        if path is None:
            return None
        a = self.world.entities[a_id]
        b = self.world.entities[b_id]
        distance_penalty = min(1.0, path.cost / 2_000_000.0)
        geographic_access = max(0.02, 1.0 - 0.7 * distance_penalty)
        ore_a = float(self.generated.ore[a_cell.y, a_cell.x])
        ore_b = float(self.generated.ore[b_cell.y, b_cell.x])
        crop_a = float(self.grain_suitability[a_cell.y, a_cell.x])
        crop_b = float(self.grain_suitability[b_cell.y, b_cell.x])
        resource_overlap = min(1.0, 0.5 * (ore_a + ore_b) + 0.25 * abs(crop_a - crop_b))
        pair = frozenset((a_id, b_id))
        grievance = min(1.0, self._conflict_grievance[pair])
        pop_a = int(a.attributes["population"])
        pop_b = int(b.attributes["population"])
        opportunity = min(1.0, max(pop_a, pop_b) / max(1, min(pop_a, pop_b)) / 4.0)
        rivalry = 0.18 + 0.5 * grievance
        fear = min(1.0, 0.15 + 0.35 * opportunity + 0.25 * grievance)
        interdependence = max(0.0, 0.45 - 0.35 * distance_penalty)
        return ConflictContext(
            actor_a=a_id,
            actor_b=b_id,
            resource_overlap=resource_overlap,
            territorial_friction=max(0.0, 0.55 - distance_penalty),
            rivalry=rivalry,
            fear=fear,
            grievance=grievance,
            opportunity=opportunity,
            interdependence=interdependence,
            kinship_inhibition=0.0,
            geographic_access=geographic_access,
        )

    def _run_conflict_processes(self, year: int) -> None:
        ids = list(self.settlement_ids)
        self.civil_rng.shuffle(ids)
        for i, a_id in enumerate(ids):
            for b_id in ids[i + 1 :]:
                if self.civil_rng.random() > 0.18:
                    continue
                context = self._conflict_context(a_id, b_id, year)
                if context is None:
                    continue
                decision = choose_conflict_action(context, self.civil_rng)
                self._conflict_actions[decision.action] += 1
                pair = frozenset((a_id, b_id))
                if decision.action == "avoid":
                    self._conflict_grievance[pair] *= 0.96
                    continue
                if decision.action == "negotiate":
                    self._conflict_grievance[pair] *= 0.78
                elif decision.action == "threaten":
                    self._conflict_grievance[pair] = min(1.5, self._conflict_grievance[pair] + 0.08)
                elif decision.action == "raid":
                    self._conflict_grievance[pair] = min(1.5, self._conflict_grievance[pair] + 0.22)
                elif decision.action == "attack":
                    self._conflict_grievance[pair] = min(1.5, self._conflict_grievance[pair] + 0.38)

                participants = (a_id, b_id)
                payload = {"action": decision.action, "pressure": round(decision.pressure, 5), "choice_probability": round(decision.probability, 5)}
                if decision.action in {"raid", "attack"}:
                    target = self.world.entities[b_id]
                    before = int(target.attributes["population"])
                    loss_fraction = self.civil_rng.uniform(0.001, 0.006) if decision.action == "raid" else self.civil_rng.uniform(0.004, 0.018)
                    losses = min(max(1, int(before * loss_fraction)), max(1, before // 20))
                    target.attributes["population"] = max(25, before - losses)
                    payload["aggregate_losses"] = losses
                self.world.record_event(Event(kind="intergroup_action", time=year, participants=participants, locations=participants, impact=0.25 + decision.pressure, payload=payload))

    def run(self) -> CivilizationSimulationResult:
        self.initialize()
        for year in range(1, self.config.years + 1):
            food_ratio = self._run_harvests(year)
            self._run_household_economy(year, food_ratio)
            self._run_demography(year, food_ratio)
            for settlement_id in self.settlement_ids:
                petition = self._experience_and_request(year, settlement_id, food_ratio[settlement_id])
                self._apply_house_action(year, settlement_id, petition)
                self._verify_reports(year, settlement_id, food_ratio[settlement_id])
            self._run_migration(year, food_ratio)
            self._run_discoveries(year)
            self._run_reproduction(year)
            self._run_mortality(year)
            self._evolve_social_network(year)
            self._evolve_households(year)
            self._run_conflict_processes(year)
            self._transmit_memory(year)

        base = SimulationResult(self.config, self.generated, self.world, tuple(self.settlement_ids))
        social = SocialSimulationResult(base, tuple(self.house_ids), tuple(self.representative_ids), self.social_memory)
        generational = GenerationalSimulationResult(
            social=social,
            kinship=self.kinship,
            network=self.network,
            person_ids=tuple(self.person_ids),
            lineage_candidates=self._lineage_candidates(),
        )
        return CivilizationSimulationResult(
            generational=generational,
            hydrology=self.hydrology,
            crop_suitability=self.grain_suitability,
            households=tuple(self.households.values()),
            conflict_actions=dict(self._conflict_actions),
        )
